- README.md
The README.md was not updated with the current package links.
> Update package urls

- package-lock.json
- package.json
- src/fetchMissing.js
- src/tokens/xdai.json
- uniswap-xdai.tokenlist.json
I created a script to fetch all mainnet tokens that crossed the bridge, so we can list them if they are validated at trustwallet or somewhere else.
> Fetch all missing bridged tokens

- src/tokens/xdai.json
I also update OWL, since the omnibridge version is not recommended to use: https://blockscout.com/poa/xdai/bridged-tokens
> Add new tokens: BID, DONUT, and FSW

- src/tokens/xdai.json
I also delete the built list, from now on the url is https://tokens.honeyswap.org.
> Add ENG, XYO, ALEPH, REN, GEAR, LOCK, PIE, TRADE, AST, KNC, SNX, OM, and xBRICK

- src/tokens/xdai.json
Website: https://ether1.org
Contact: ethan@ether1.org
Honeyswap Pair: https://info.honeyswap.org/pair/0x1b988C21bc7E920A13dC0C96C616bAAb3D678d47
> Add Wrapped ETHO Token

- src/tokens/xdai.json
> feat(add): ZRX

- src/tokens/xdai.json
paired with @Monstrosity1
close #39
> feat(list): add a bunch of new tokens

- src/tokens/xdai.json
> feat(add) : BTCCB

- src/tokens/xdai.json
> feat(add): AUDIO

- src/tokens/xdai.json
> feat(add): ROBOT

- src/tokens/xdai.json
> fixed xSEED decimals

- src/tokens/xdai.json
> feat(add): $HAUS

- src/tokens/xdai.json
> feat(add): bDAI

- src/tokens/xdai.json
see #94 
/cc: @crisog , @felixbbertrand
> add FRACTION #94

- src/tokens/xdai.json
> feat(add): HIVESHARE

- src/tokens/xdai.json
> feat(add): BUSD

- src/tokens/xdai.json
token was left off the token list. This PR points to the project site and svg logo.
> adding logoURI for LTI token

- src/buildList.js
- src/tokens/polygon.json
- src/tokens/xdai.json
- test/uniswap-default.test.js
This PR adds Polygon network to our token list.
> feat: add Polygon to default token list

- src/tokens/xdai.json
> patch(logoURI): MRP

- src/tokens/xdai.json
Adds $PANTS token and a new logo for PRTCLE
> Add Sweatpants and change PRTCLE logo

- src/tokens/polygon.json
Adding ShapeShift FOX on Polygon (currently listed only for xDai on HoneySwap)
> feat(add): Polygon (ShapeShift FOX)

- src/tokens/xdai.json
> feat(add): PUNK

- src/tokens/polygon.json
Add Minerva Wallet SuperToken (MIVA) and Own a fraction (FRACTION) on Polygon
> Add MIVA and FRACTION on Polygon

- src/tokens/xdai.json
We bridged VitaDAO to Gnosis Chain, and launched a pool on HoneySwap, updating here so people can see our icon.
> Update xdai.json with VitaDAO icon

- src/tokens/xdai.json
> feat(add): sGNO, rGNO

- src/tokens/xdai.json
> feat(add): MPS
